### PR TITLE
⚡ feat(team generator): added all necessary overview pages

### LINKED ISSUE #3: ⚡ Team generator: overview pages
- [x] Courses
- [x] Classes
- [x] Class details (student overview)
- [x] Class home (for when class has teams already)

### PR DESCRIPTION
**Pull request by noyamirai**
Hi! 👋 

In the repo of my very own team generator feature I forgot to implement the whole 'routes' structure, as in putting routes in a separate folder? I saw you implemented this into your feature project, which I think looked neat. It would help keep our routes organized and make everything look clean.

For now, I just added my routes into `server.js` because I am just not really sure how to set it up? The way I understand this routing principle is that you define a 'global' or 'base' path for the user to navigate to, as demonstrated in the example below:

```javascript
app.use('/:username', require('./routes/user'));
```
 and this path (`/:username`) is then added as a baseUrl to whatever request path the router is listening to in the routes folder, like so:

```javascript
router.get(`/courses`, (req, res) => { ... }); //path would be: /:username/courses
```

So, my main point of confusion for now is not being sure how to correctly organize everything, since I have been getting most of my data through the `/:username` path, meaning the `./routes/user.js` file  would still be pretty big/long (basically the same as putting it in `server.js`)? Or would this be the correct way of handling it?

Let me know your thoughts!!

### CODE REVIEW

**Comment by Aidan98** [comment]
It's better to put the features in routes, makes things more organized and prevents files like server.js from becoming to bloated and difficult to read. If I understand correctly the path "/:username" won't be necessary as when you create an account and log in your as your dashboard / homescreen will be unique to those are logged in because they need to be authenticated

**Comment by Aidan98** [comment]
I can help with creating routes, as I will be creating my feature in a route.

**Review by Aidan98 — APPROVED** [review]
Pog

**Comment by noyamirai** [comment]
> It's better to put the features in routes, makes things more organized and prevents files like server.js from becoming to bloated and difficult to read. If I understand correctly the path "/:username" won't be necessary as when you create an account and log in your as your dashboard / homescreen will be unique to those are logged in because they need to be authenticated

Yes, for creating accounts the `/:username` path is not necessary, except when logging into your account I think it is... I'm not sure how it would work with the session tokens etc but I think we could just direct them to the `/:username` path and our `./routes/user.js` will listen and will basically catch it? 🤔  Only issue I have with the routes thing is that `req.params` no longer gives me an object back meaning I would not be able to get `req.params.username`

**Pull request merged**
