### PR TITLE
Feature: user login complete

### LINKED ISSUE #9: ⚡ Login
Feature: allow the user to login to CMD-online

### PR DESCRIPTION
**Pull request by Aidan98**
Users can now login via `/users/login/`. Forgot to switch from branch before working on the next feature, will do so now 😬.

### CODE REVIEW

**Comment by Aidan98** [comment]
Conflicts are that I uncommented required modules in `server.js` and added a class to `body` and `form` in `login.ejs`. Can't resolve it without merging so I will wait for your @noyamirai review before I do it

**Review by noyamirai — CHANGES_REQUESTED** [review]
Well done!! You can just merge everything once you fix the merge conflicts 👍

**Comment by noyamirai** [comment]
oh wait do i have to do it LOL

**Review by noyamirai — APPROVED** [review]

**Comment by Aidan98** [comment]
Aiight thnx^^

**Comment by noyamirai** [comment]
big pog

**Pull request merged**
