### PR TITLE
Edit account

### LINKED ISSUE #61: ⚡ Profile: edit account details
Grant the user the ability to edit their username, name and password

### PR DESCRIPTION
**Pull request by Aidan98**
Users can now edit their account details. Also fixed the issue where the database would not take in the profile picture submitted by the user ( would default to `uploads/default-profile_pic.png` even when the user uploaded an image).

### CODE REVIEW

**Comment by Aidan98** [comment]
As mentioned on whatsapp @noyamirai this error persists: 

```
Preview URL: false
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.setHeader (node:_http_outgoing:576:11)
    at ServerResponse.header (/mnt/c/Users/Aidan/Documents/repo_team/cmd-online/node_modules/express/lib/response.js:776:10) 
    at ServerResponse.send (/mnt/c/Users/Aidan/Documents/repo_team/cmd-online/node_modules/express/lib/response.js:170:12)   
    at done (/mnt/c/Users/Aidan/Documents/repo_team/cmd-online/node_modules/express/lib/response.js:1013:10)
    at tryHandleCache (/mnt/c/Users/Aidan/Documents/repo_team/cmd-online/node_modules/ejs/lib/ejs.js:278:5)
    at View.exports.renderFile [as engine] (/mnt/c/Users/Aidan/Documents/repo_team/cmd-online/node_modules/ejs/lib/ejs.js:489:10)                                                                                                                         :10)      
    at View.render (/mnt/c/Users/Aidan/Documents/repo_team/cmd-online/node_modules/express/lib/view.js:135:8)
    at tryRender (/mnt/c/Users/Aidan/Documents/repo_team/cmd-online/node_modules/express/lib/application.js:640:10)
    at Function.render (/mnt/c/Users/Aidan/Documents/repo_team/cmd-online/node_modules/express/lib/application.js:592:3) 
```

**Comment by Aidan98** [comment]
It probably has something to do with `node mailer`..... 👀

**Review by noyamirai — APPROVED** [review]
Sick! I'll test everything and try to fix the node mailer error. Tejo might have called a redirect or something causing the server to send a response twice (hence the error)... When everything works again I will deploy it onto heroku!

**Comment by noyamirai** [comment]
@Aidan98 fixed the code! After registration a redirect happened, which is normal, but then in Tejo's code he tried to render login after the mail was sent which was causing the error! Also fixed the duplicate student creation error, the create doc operation for student was called twice :p

**Pull request merged**
