### PR TITLE
⚡ feat(overview): created routes and cleaned code

### LINKED ISSUE #7: ⚡ Team generator: add to routes

### PR DESCRIPTION
**Pull request by noyamirai**
As discussed via WhatsApp, the overview pages now go through `./routes/overviews` instead of `server.js`

I also cleaned my code a little bit because I noticed some old/unnecessary lines

### CODE REVIEW

**Comment by Aidan98** [comment]
Looks good, now `server.js` should look more organized 👍🏽.

**Comment by Aidan98** [comment]
Where does the User assign a class or course to themselves? in  the `Dashboard`?

**Comment by noyamirai** [comment]
> Where does the User assign a class or course to themselves? in the `Dashboard`?

hmm not quite sure yet, I was thinkingaybe after you create your account you’re met with a screen that shows suggestions for you to give live to your profile such as “add class” etc? I think @TejoBurgboy will be picking this up

**Comment by Aidan98** [comment]
Alrighty

**Pull request merged**
